---
    - hosts: db
      become: true
      tasks:
        - name: Ensure MariaDB-server is installed.
          ansible.builtin.package:
            name: mariadb-server
            state: present
        - name: mariadb on boot
          ansible.builtin.service:
            name: mariadb
            enabled: true
            state: started
