---
    - hosts: db
      become: true
      tasks:
        - name: Ensure MariaDB-server is installed.
          ansible.builtin.package:
            name: mariadb-server
            state: present
        - name: mariadb on boot
          ansible.builtin.service:
            name: mariadb
            enabled: true
            state: started
        - name: install  python3 mysql
          ansible.builtin.package:
            name: python3-PyMySQL
            state: present
            update_cache: yes

        - name: Create MariaDB user
          community.mysql.mysql_user:
            name: webappuser
            password: secretpassword
            host: localhost
            priv: '*.*:ALL'
            state: present
            login_user: root
            login_unix_socket: /var/lib/mysql/mysql.sock

        - name: Try to create database
          community.mysql.mysql_db:
            name: webapp
            login_user: webappuser
            login_unix_socket: /var/lib/mysql/mysql.sock
            state: present

