---
- name: Configure nginx for HTTPS
  hosts: web
  become: true
  tasks:
    - name: Deploy HTTPS configuration file from template
      ansible.builtin.template:
        src: example.internal.conf.j2
        dest: /etc/nginx/conf.d/example.internal.conf
        owner: root
        group: root
        mode: '0644'

    - name: Check nginx config syntax
      ansible.builtin.command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Fail if nginx config test failed
      ansible.builtin.fail:
        msg: "Nginx config test failed: {{ nginx_test.stderr }}"
      when: nginx_test.rc != 0

    - name: Restart nginx service to apply new configuration
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Create a directory structure under /var/www/example.internal
      ansible.builtin.file:
        path: /var/www/example.internal/html
        state: directory
        mode: '0755'

    - name: Upload files/index.html to /var/www/example.internal/html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/example.internal/html/index.html
        owner: root
        group: root
        mode: '0644'
      register: result

    - name: Debug upload result
      ansible.builtin.debug:
        var: result

    - name: Restart nginx if index.html was changed
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: result.changed

